### PR TITLE
243 entrypoint for meta

### PR DESCRIPTION
**Pull request by JoeZ99**
**WARNING** apply this PR **after** #247 is merged..

also, wait for @ecoslado approval 

@ecoslado , Please check a few things first:

  - I've moved some things around:
    * I think `lib/` directory is for code that works as a library and can function autonomously, rather that code intended to use as a mixin (which, if you want, can be almost called "code leaflets"). So I made the following changes. Also, my initial approach of calling the mixin for the `CommonsController` as `CommonsHelper` and put it under the `helpers/` directory is wrong for the same reason.
    * The `MetaController` class used as a mixim to add one method to `CommonsController`  is renamed as `CommonsControllerMixin` and located in `controlles/` directory..as `MetaAttributesControllerMixin` and located in `controlles/` directory..
    * The `CommonsHelper` class used as a mixim to add methods to  `CommonsController`  is renamed as `CommonsControllerMixin` and located in `controlles/` directory..as `CommonsControllerMixin` and located in `controlles/` directory..

  - I'm not sure if the format for sending the json in order to update a meta attribute is right. I'm using 
  ````json
  {
    "data": {
      "attributes": {
        "value": "new val"
      }
    }
}
  ````

lease feel free to discuss.

### CODE REVIEW

**Comment by ecoslado** [comment]
The Mixins stuff: ok.

I'm not really sure about the way you could sent the meta_attributes. You can consider meta_attributes as a relation or maybe use the meta key that offers the JSON specification. 

Have a look at this: http://jsonapi.org/

**Comment by JoeZ99** [comment]
@ecoslado 
I've read the specification. It's quite a reading btw.

As it says, `meta` should be a top-level keey of a resource object specification, that is:

```json
{
  "data": {
    "id": "9",
    "type": "invoice"
  },
  "meta": {
    "note": "for nacho"
  }
}
````

According to this  you are adding meta attributes to the invoice with the wrong format , as seen in  https://github.com/siwapp/siwapp/blob/master/app/controllers/api/v1/commons_controller.rb#L51

  - for one, I think that's unnecessary nested. We could add meta keys without the extra `attributes` key which is fine and jsonapi compliant, but as I see it, too nested. This way it would be:

````json
{
  "data": {
    "id": "9",
    "type": "invoice"
  },
  "meta": {
    "note": "for nacho",
    "not_nested_attrib": "some_value"
  }
}
````

  - the simplest way of updating a meta attribute if we are in paranoid mode would be then:

````
PUT http://siwapp.org/api/v1/invoices/9
````

````json
{
  "data": {
    "id": "9",
    "type": "invoice"
  },
  "meta": {
    "too_nested_1": "some_value"
  }
}
````


  - Maybe it's worth to "tweak" a little the jsonapi and update mate independelty as jsonapi allows to do with relationships:

````
PUT http://siwapp.org/api/v1/invoices/9/meta
````

````json
{
  "data": {'
    label1": "value1"
  }
}
```
I'm not pretty sure, actually.

It's just that I would like to be able to atomically add or update a meta attribute with any fuzz. But I guess that can't be done in an orthodox way.

thoughts??

**Comment by JoeZ99** [comment]
@ecoslado

After reading the jsonapi specs, I realized almost nothing has to be done. I've relocated the place of the meta stuff in invoice creation an updating. No longer `data[attributes][meta_attributes]`, but `data[meta]` which is what's specified in jsonapi. after that a minimal change in the `api_v1_invoices_controller.rb` file was enough. As discussed with you by mail, I opted for not being able to remove any meta attribute during update (it was already like that), we can discuss the options on the email I sent you.

**Comment by JoeZ99** [comment]
@peillis please ask @ecoslado to review this PR so you can merge it

**Comment by ecoslado** [comment]
Sorry for the delay @JoeZ99. Using `attributes.meta_attributes` is ok for me. Updating the whole meta_attributes set is more orthodox, but I think it can be annoying when you have stored `accounting_code` and `accounting_number` and just need to add `message`. In this case, if you don't have the accounting stuff, you should request the invoice before. So we could adopt the convention that setting to `null` is the same as removing the meta_attribute.

**Comment by ecoslado** [comment]
Ok, once I've done some changes in doofinder siwapp client, I'll merge it.

**Pull request merged**
